### ISSUE TITLE
The example is awesome but has a little issue

### ISSUE THREAD

**Issue by RuChiang** [strangerlabs/webauthn#6]
Hi there,

First of all, this is an really AWESOME repo!!
It guided me through some of the implementations that I would not have even known!

Just to point out this little issue when I am running the example. I think in Webauthn.js, it's better to modify line 30, 31
`
usernameField: 'username',
userFields: ['username', 'name'],
`
So that there won't be mismatch between the parameters from the front-end and back-end

Best,

Ru

**Comment by EternalDeiwos** [comment]
Hi @RuChiang, thanks for taking a look at our repo, we're glad to be of assistance

Regarding your suggestion, those field names are actually taken directly from the [WebAuthn API Specification](https://www.w3.org/TR/webauthn/#dictdef-publickeycredentialuserentity) so we think it makes the most sense to leave those as the defaults. We also recognise that it would not be a good idea to restrict the field names, which is why we allowed for the possibility of aliasing them with a mapping as you can see [here](https://github.com/strangerlabs/webauthn/blob/master/example/server.js#L45-L49).

Happy hacking

**Comment by RuChiang** [comment]
@EternalDeiwos Thanks for answering!! 
I just checked the webpage and I agree with you.

Good work indeed!!
